// Generated by `wit-bindgen` 0.17.0. DO NOT EDIT!
#ifndef __BINDINGS_LAMBDA_H
#define __BINDINGS_LAMBDA_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} lambda_string_t;

// Imported Functions from `manetu:lambda/sparql@0.0.2`
extern void manetu_lambda_sparql_query(lambda_string_t *expr, lambda_string_t *ret);

// Exported Functions from `manetu:lambda/guest@0.0.2`
void exports_manetu_lambda_guest_handle_request(lambda_string_t *request, lambda_string_t *ret);
uint32_t exports_manetu_lambda_guest_malloc(uint32_t len);
void exports_manetu_lambda_guest_free(uint32_t ptr);

// Helper Functions

// Transfers ownership of `s` into the string `ret`
void lambda_string_set(lambda_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void lambda_string_dup(lambda_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void lambda_string_free(lambda_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
