// Generated by `wit-bindgen` 0.17.0. DO NOT EDIT!
#include "lambda.h"


__attribute__((__import_module__("manetu:lambda/sparql@0.0.2"), __import_name__("query")))
extern void __wasm_import_manetu_lambda_sparql_query(int32_t, int32_t, int32_t);
__attribute__((__weak__, __export_name__("cabi_post_manetu:lambda/guest@0.0.2#handle-request")))
void __wasm_export_exports_manetu_lambda_guest_handle_request_post_return(int32_t arg0) {
  if ((*((int32_t*) (arg0 + 4))) > 0) {
    free((void*) (*((int32_t*) (arg0 + 0))));
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void lambda_string_set(lambda_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void lambda_string_dup(lambda_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void lambda_string_free(lambda_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

void manetu_lambda_sparql_query(lambda_string_t *expr, lambda_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_manetu_lambda_sparql_query((int32_t) (*expr).ptr, (int32_t) (*expr).len, ptr);
  *ret = (lambda_string_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

__attribute__((__export_name__("manetu:lambda/guest@0.0.2#handle-request")))
int32_t __wasm_export_exports_manetu_lambda_guest_handle_request(int32_t arg, int32_t arg0) {
  lambda_string_t arg1 = (lambda_string_t) { (uint8_t*)(arg), (size_t)(arg0) };
  lambda_string_t ret;
  exports_manetu_lambda_guest_handle_request(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int32_t*)(ptr + 4)) = (int32_t) (ret).len;
  *((int32_t*)(ptr + 0)) = (int32_t) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("manetu:lambda/guest@0.0.2#malloc")))
int32_t __wasm_export_exports_manetu_lambda_guest_malloc(int32_t arg) {
  uint32_t ret = exports_manetu_lambda_guest_malloc((uint32_t) (arg));
  return (int32_t) (ret);
}

__attribute__((__export_name__("manetu:lambda/guest@0.0.2#free")))
void __wasm_export_exports_manetu_lambda_guest_free(int32_t arg) {
  exports_manetu_lambda_guest_free((uint32_t) (arg));
}

extern void __component_type_object_force_link_lambda(void);
void __component_type_object_force_link_lambda_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_lambda();
}
